version: '3'

services:
  node-app:
    image: node:14
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - 'redis-server'

  redis-server:
    image: 'redis'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
